/*** This file... ACEModeNamesAutoGenerated.h is AUTOGENERATED.  See target 'UpdateAce'*/ 


  typedef NS_ENUM (NSUInteger, ACEMode) {

 	ACEModeABAP,	ACEModeActionScript,	ACEModeADA,	ACEModeAsciiDoc,	ACEModeAssembly_x86,	ACEModeAutoHotKey,	ACEModeBatchFile,	ACEModeC9Search,	ACEModeC_Cpp,	ACEModeClojure,	ACEModeCobol,	ACEModecoffee,	ACEModeColdFusion,	ACEModeCSharp,	ACEModeCSS,	ACEModeCurly,	ACEModeD,	ACEModeDart,	ACEModeDiff,	ACEModeDot,	ACEModeErlang,	ACEModeEJS,	ACEModeForth,	ACEModeFTL,	ACEModeGlsl,	ACEModegolang,	ACEModeGroovy,	ACEModeHAML,	ACEModeHandlebars,	ACEModeHaskell,	ACEModehaXe,	ACEModeHTML,	ACEModeHTML_Ruby,	ACEModeINI,	ACEModeJack,	ACEModeJade,	ACEModeJava,	ACEModeJavaScript,	ACEModeJSON,	ACEModeJSONiq,	ACEModeJSP,	ACEModeJSX,	ACEModeJulia,	ACEModeLaTeX,	ACEModeLESS,	ACEModeLiquid,	ACEModeLisp,	ACEModeLiveScript,	ACEModeLogiQL,	ACEModeLSL,	ACEModeLua,	ACEModeLuaPage,	ACEModeLucene,	ACEModeMakefile,	ACEModeMATLAB,	ACEModeMarkdown,	ACEModeMySQL,	ACEModeMUSHCode,	ACEModeNix,	ACEModeObjectiveC,	ACEModeOCaml,	ACEModePascal,	ACEModePerl,	ACEModepgSQL,	ACEModePHP,	ACEModePowershell,	ACEModeProlog,	ACEModeProperties,	ACEModeProtobuf,	ACEModePython,	ACEModeR,	ACEModeRDoc,	ACEModeRHTML,	ACEModeRuby,	ACEModeRust,	ACEModeSASS,	ACEModeSCAD,	ACEModeScala,	ACEModeScheme,	ACEModeSCSS,	ACEModeSH,	ACEModeSJS,	ACEModeSpace,	ACEModesnippets,	ACEModeSoy_Template,	ACEModeSQL,	ACEModeStylus,	ACEModeSVG,	ACEModeTcl,	ACEModeTex,	ACEModeText,	ACEModeTextile,	ACEModeToml,	ACEModeTwig,	ACEModeTypescript,	ACEModeVBScript,	ACEModeVelocity,	ACEModeVerilog,	ACEModeXML,	ACEModeXQuery,	ACEModeYAML,

 	ACEModeCount  // keep track of the enum size automatically
 };

